modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "createdeco"
version = "${version}"
displayName = "Create Deco"
authors = "Kayla, Talrey"
description = '''
Decorative options for your Create factory
'''
logoFile = "icon.png"

[[dependencies.createdeco]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createdeco]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.createdeco]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"
